services:
  app:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204

    container_name: meudb
    ports:
      - 27017:27017
    volumes:
      - ./:/data/db
    tty: true
    stdin_open: true